export const CREATE_RECIPE_REQUEST = "CREATE_RECIPE_REQUEST";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_FAIL = "CREATE_RECIPE_FAIL";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const GET_RECIPE = "GET_RECIPE";
export const GET_RECIPES_BY_CHEF = "GET_RECIPES_BY_CHEF";
export const SET_SRC_DATA = "SET_SRC_DATA";
