export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const RESET_CART = "RESET_CART";
export const DECREASE_COUNT = "DECREASE_COUNT";
export const INCREASE_COUNT = "INCREASE_COUNT";
export const GET_CHOSEN_CHEF_PROFILE = "GET_CHOSEN_CHEF_PROFILE";

export const CREATE_RECIPE = "CREATE_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const GET_RECIPE = "GET_RECIPE";
export const RESET_RECIPES = "RESET_RECIPES";
export const GET_RECIPES_BY_CHEF = "GET_RECIPES_BY_CHEF";
